### ISSUE TITLE
Bad color encoding with phpunit-pretty-result-printer enable

### ISSUE THREAD

**Issue by LespiletteMaxime** [gerardroche/sublime-phpunit#77] opened 2018-01-10 10:48 UTC
Hello,

Thanks for this very usefull plugin.

I tried to use https://github.com/mikeerickson/phpunit-pretty-result-printer, result is fine in terminal
but display is broken in sublime-phpunit. Just wonder if there is a possible fix for this or if I should avoid using pretty-result.

Here are screenshot from the same test launched in terminal and in sublime-text

in sublime-phpunit :
![capture du 2018-01-10 11-39-15](https://user-images.githubusercontent.com/2920479/34768422-121622bc-f5fb-11e7-9c06-a783abaac16d.png)

in terminal :
![capture du 2018-01-10 11-39-40](https://user-images.githubusercontent.com/2920479/34768461-28939876-f5fb-11e7-97c3-e279464bf358.png)

thanks

**Comment by gerardroche** [comment] 2018-01-11 09:30
PHPUnitKit isn't aware of [CD PHPUnit Pretty Result Printer](https://github.com/mikeerickson/phpunit-pretty-result-printer) so that would be a new feature.

We can get shot of those strange characters by disabling color by default in ST. The output panel will still have color because we color the build result based on the text output.

In your settings, `Menu > Preferences > Settings`, add:

```
	"phpunit.options":
	{
		"colors=never": true
	},
```

That essentially tell PHPUnitKit to pass the option `--colors=never` when running PHPUnit. 

You can other options, for example if you wanted to disabled code coverage generation by default in ST:

```
	"phpunit.options":
	{
		"no-coverage": true,
		"colors=never": true
	},
```

That's like running `phpunit --no-coverage --colors=never`.

There is a toggle command for toggling options, like `no-coverage`, on the fly. You can find them in the Command Palette prefixed with "PHPUnit: ".

**Comment by gerardroche** [comment] 2018-01-11 10:56
There is actually an issue in the pretty printer where you can't disable the colors. I've sent a PR. Hopefully it'll get merged soon enough

**Comment by LespiletteMaxime** [comment] 2018-01-11 11:03
Hello,

I applied your patch to Printer.php and add config in my settings and I confirm it fix the bug well done and thanks

**Comment by godbout** [comment] 2018-11-14 08:19
Can't really make it work here. Some colors are handled, some are still gibberish. Any info I could send or any advise of where to look for the problem? Thanks.

**Comment by godbout** [comment] 2018-12-29 12:34
This is what I currently have, with colors disabled:

![serverstest_php_ _hahahaha](https://user-images.githubusercontent.com/121373/50538343-1159ff00-0ba9-11e9-9a8a-60c2e69c58f0.png)

**Comment by LespiletteMaxime** [comment] 2019-01-16 10:48
I confirm issue is back

**Comment by gerardroche** [comment] 2019-01-17 13:37
@godbout @LespiletteMaxime Can you post some debug information? See https://github.com/gerardroche/sublime-phpunit#debugging on how to enable debug mode and get the log. It will look something like this:

```
PHPUnit: view 15 /home/code/projects/sublime-phpunit-testing/phpunit.xml.dist
PHPUnit: run phpunit with working_dir=None, file=None, options=None
PHPUnit: find configuration for '/home/code/projects/sublime-phpunit-testing/phpunit.xml.dist'
PHPUnit: found 3 folders ['/home/code/projects/sublime-phpunit-testing', '/home/gerard/projects/symlinks/dotfiles', '/home/code/.config/sublime-text-3/Packages/PHPUnitKit']
PHPUnit: found 3 common ancestors ['/home/code/projects/sublime-phpunit-testing', '/home/code/projects', '/home/gerard/projects']
PHPUnit: candidate configuration files ['phpunit.xml', 'phpunit.xml.dist']
PHPUnit: looking at '/home/code/projects/sublime-phpunit-testing'
PHPUnit: found file '/home/code/projects/sublime-phpunit-testing/phpunit.xml.dist'
PHPUnit: workingdir '/home/code/projects/sublime-phpunit-testing'
PHPUnit: executable '/home/code/projects/sublime-phpunit-testing/vendor/bin/phpunit'
PHPUnit: options {'colors=always': True}
PHPUnit: env {}
PHPUnit: cmd ['/home/code/projects/sublime-phpunit-testing/vendor/bin/phpunit', '--colors=always']
PHPUnit: checking if color scheme 'Packages/MonokaiFree/MonokaiFree.tmTheme' needs support
PHPUnit: color scheme has plugin support
```

**Comment by gerardroche** [comment] 2019-01-17 14:03
@godbout @LespiletteMaxime  This is a regression in Pretty Printer, see https://github.com/mikeerickson/phpunit-pretty-result-printer/issues/137.

**Closed by gerardroche** 2019-01-17 14:03 UTC

**Comment by godbout** [comment] 2019-01-17 14:53
Oooohhh. Thanks for checking @gerardroche. I didn't check the code of pretty-printer because I had never been able to make it work with your plugin while others could, so I thought I was the one doing something wrong. I'll check the code there then and see if I may help. Thank you!

**Comment by LespiletteMaxime** [comment] 2019-01-19 09:08
Hi here is the output you asked, 

I use phpunit-result-printer "^0.24.1"  with phpunit 7.0
I got the --colors=never enable in my output

```
PHPUnit: view 17 /home/max/Sites/code/tests/Unit/GESTest.php
PHPUnit: run nearest
PHPUnit: run phpunit with working_dir=None, file=/home/max/Sites/code/tests/Unit/GESTest.php, options={}
PHPUnit: find configuration for '/home/max/Sites/code/tests/Unit/GESTest.php'
PHPUnit: found 1 folders ['/home/max/Sites/code']
PHPUnit: found 3 common ancestors ['/home/max/Sites/code/tests/Unit', '/home/max/Sites/code/tests', '/home/max/Sites/code']
PHPUnit: candidate configuration files ['phpunit.xml', 'phpunit.xml.dist']
PHPUnit: looking at '/home/max/Sites/code/tests/Unit'
PHPUnit: looking at '/home/max/Sites/code/tests'
PHPUnit: looking at '/home/max/Sites/code'
PHPUnit: found file '/home/max/Sites/code/phpunit.xml'
PHPUnit: workingdir '/home/max/Sites/code'
PHPUnit: executable '/home/max/Sites/code/vendor/bin/phpunit'
PHPUnit: options {'colors=never': True}
PHPUnit: file tests/Unit/GESTest.php
PHPUnit: env {}
PHPUnit: cmd ['/home/max/Sites/code/vendor/bin/phpunit', '--colors=never', 'tests/Unit/GESTest.php']
PHPUnit: checking if color scheme 'Packages/User/Color Highlighter/themes/Material-Theme.tmTheme' needs support
PHPUnit: auto generated color scheme = Cache/PHPUnitKit/color-schemes/themes__Material-Theme.hidden-tmTheme
```

**Comment by mikeerickson** [comment] 2019-01-21 00:03
Hey gang, I am working on this issue and I am not quite sure where the problem occurs.  Can any of you who this has impacted point me to more information?  I have tested locally and when I use `colors=never` there is truly no color?  I am surely not saying that there is not a problem, I am just trying to find a way to reproduce this issue.

I am puzzled as to why it works as expected in terminal, phpstorm, vscode but differs in Sublime.  Any clues you can all supply would be appreciated so that I can track down and fix this issue.

**Comment by godbout** [comment] 2019-01-21 11:08
Time to get the hands dirty 🛢️🛢️🛢️I'm gonna have a look.

Although would it be possible that the issue comes from sublime-phpunit itself? @gerardroche I've found that some commands seem to be passed correctly to phpunit but it does nothing. (--coverage-text for example. If passed with a typo phpunit knows that the option is wrong, but passed without typo is does nothing although it obviously is recognized.)

**Comment by godbout** [comment] 2019-01-21 12:02
@mikeerickson not sure if it helps but this is what I have at the moment:

When calling `phpunit --colors=never` from the terminal with the original printer, all colors are disabled. With `pretty-printer`, some colors are still active. See below.

![guill_guill-imac____development_peeing__zsh_](https://user-images.githubusercontent.com/121373/51473382-2f390f00-1db7-11e9-94d5-dab75771f2db.png)

Then in the source, there seems to have several places where the color is kinda hardcoded (not the final color, but at least the characters that appear in Sublime Text when the colors doesn't work): https://github.com/mikeerickson/phpunit-pretty-result-printer/blob/efac6389486641fd3390180c5e0eb4bec5f4cd9e/src/ResultPrinter71.php#L178

**Comment by gerardroche** [comment] 2019-01-21 12:11
@godbout in your screenshot, you are using `--color=never` instead of `--colors=never`.

**Comment by godbout** [comment] 2019-01-21 12:15
🤦️ sorry about. New screenshot. Still having colors at the top though.

![guill_guill-imac____development_peeing__zsh__and_bad_color_encoding_with_phpunit-pretty-result-printer_enable_ _issue__77_ _gerardroche_sublime-phpunit-2](https://user-images.githubusercontent.com/121373/51474111-3d882a80-1db9-11e9-840c-591f4152c183.png)

To confirm, I have `"colors=never": true` in my Sublime Text settings.

![preferences_sublime-settings_ _user](https://user-images.githubusercontent.com/121373/51474125-4bd64680-1db9-11e9-9e9a-04efc0b5def7.png)

**Comment by gerardroche** [comment] 2019-01-21 12:18
Here is PHPUnit on the terminal without pretty printer:

![screenshot from 2019-01-21 12-14-59](https://user-images.githubusercontent.com/44148/51474115-32f87180-1d76-11e9-80e1-b50a1d1c2414.png)

Here it is with pretty printer:

![screenshot from 2019-01-21 12-15-47](https://user-images.githubusercontent.com/44148/51474134-46a3d800-1d76-11e9-8601-052f6d7fbdde.png)

Pretty printer is outputting some things with color. Pretty is not using the PHPUnit configuration to determine if colors should be output.

**Comment by godbout** [comment] 2019-01-21 12:44
Yes, well, it shouldn't, right? It should mean that the colors are enforced in `pretty printer`.

**Comment by godbout** [comment] 2019-01-21 12:46
Anyways I'm just sending this for debugging. I use mainly phpunit through your plugin. With or without the colors off, this is what I still have currently:

![sitetest_php_ _peeing](https://user-images.githubusercontent.com/121373/51475532-91950e00-1dbd-11e9-9c18-4dc7e1044339.png)

**Comment by mikeerickson** [comment] 2019-01-21 15:20
Hey gang, thanks for the information, I now know what is happening.  I will debug this today and get a new version tagged as soon as possible

**Comment by mikeerickson** [comment] 2019-01-26 18:35
Hey gang, I have published/tagged a new version which should make this all good.

https://github.com/mikeerickson/phpunit-pretty-result-printer/releases/tag/v0.25.0

Output w/o color

![image](https://user-images.githubusercontent.com/183153/51791321-0c5f7f80-2156-11e9-9ef2-73a3e687d54c.png)

Output w/ color

![image](https://user-images.githubusercontent.com/183153/51791327-20a37c80-2156-11e9-8008-c803058535cf.png)

**Comment by godbout** [comment] 2019-01-27 07:32
@mikeerickson works nicely with @gerardroche's plugin. All ANSI codes are gone. Thanks a lot!

@gerardroche btw, have you ever considered that plugin to handle ANSI colors in the output panel for your plugin? https://github.com/aziz/SublimeANSI#using-this-plugin-as-a-dependency-for-your-pluginbuild-output-panel 
Maybe there's something possible to do there?

**Comment by gerardroche** [comment] 2019-01-29 22:11
@godbout I'm not sure I like the overhead of supporting ansi codes.

**Comment by godbout** [comment] 2019-01-31 03:19
@gerardroche fair enough :D thanks for all the help!
